// ********* DO NOT EDIT *********
// This file was generated by github.com/seamia/tools/assets/cmd/assets
// on Wednesday, 03-Aug-22 15:52:56 CEST

package main

import "github.com/seamia/tools/assets"

var staticAssets = assets.AssetRoot{

}

func init() {
	assets.Assign(staticAssets)
}
